image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.25-build.2
  pullPolicy: IfNotPresent

replicaCount: 5

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: true

persistentLog:
  size: 10Gi

patroni:
  replicaCount: 3

  persistentVolume:
    size: 10Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: false

rollingUpdate:
  maxSurge: 3
