replicaCount: 2

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: true

maintenancePage:
  enabled: false
  active: false

patroni:
  replicaCount: 2

  persistentVolume:
    size: 1Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: false

rollingUpdate:
  maxSurge: 2
