image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.25-build.2
  pullPolicy: IfNotPresent

replicaCount: 0

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: false

persistentLog:
  size: 15Gi

patroni:
  replicaCount: 3

  persistentVolume:
    size: 10Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: false

readinessProbe:
  enabled: true
  verification: script
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 12
