replicaCount: 0

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

persistentLog:
  size: 0.5Gi

maintenancePage:
  enabled: false
  active: false

patroni:
  replicaCount: 1

  persistentVolume:
    size: 0.5Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: true

  # transportServerClaimConfig:
  #   enabled: true
  #   interval: 10
  #   timeout: 10
