replicaCount: 1

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

maintenancePage:
  enabled: false
  active: false

patroni:
  replicaCount: 1

  persistentVolume:
    size: 0.5Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: false
