replicaCount: 0

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

maintenancePage:
  enabled: false
  active: false

persistentLog:
  size: 2Gi

patroni:
  replicaCount: 2

  persistentVolume:
    size: 0.5Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: true
