image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.39-build.1
  pullPolicy: IfNotPresent

replicaCount: 0

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: false

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

maintenancePage:
  enabled: true
  active: true

podDisruptionBudget:
  enabled: false
  minAvailable:
  maxUnavailable:

patroni:
  replicaCount: 3

  persistentVolume:
    size: 1Gi

  podDisruptionBudget:
    enabled: false

  transportServerClaim:
    enabled: false

rollingUpdate:
  maxSurge: 2
