image:
  repository: ghcr.io/bcgov/sso
  tag: 7.6.39-build.2
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8443

tls:
  enabled: true

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

maintenancePage:
  enabled: false
  active: false

patroni:
  replicaCount: 3

  persistentVolume:
    size: 1Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: true
