replicaCount: 2

additionalServerOptions: >-
  -Dkeycloak.profile.feature.impersonation=disabled
  -Djboss.persistent.log.dir=/var/log/eap
  -Djgroups.dns.query=sso-keycloak-ping.e4ca1d-dev.svc.cluster.local

extraEnvs:
  - name: KC_HOSTNAME_URL
    value: https://dev.sandbox.loginproxy.gov.bc.ca/auth/
  - name: KC_HOSTNAME_ADMIN_URL
    value: https://dev.sandbox.loginproxy.gov.bc.ca/auth/
  ## If debugging needs to be done without the use of the vanity urls, use the following KC_HOSTNAMES
  # - name: KC_HOSTNAME_URL
  #   value: https://sso-keycloak-e4ca1d-dev.apps.gold.devops.gov.bc.ca/auth/
  # - name: KC_HOSTNAME_ADMIN_URL
  #   value: https://sso-keycloak-e4ca1d-dev.apps.gold.devops.gov.bc.ca/auth/

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.8
    memory: 1Gi

maintenancePage:
  enabled: false
  active: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable:

patroni:
  replicaCount: 3

  persistentVolume:
    size: 1Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: true

rollingUpdate:
  maxSurge: 1
