FROM python:3.12.6-alpine3.19

WORKDIR /app

RUN python -m pip install --upgrade pip

ARG POETRY_VERSION=1.8.3

RUN apk add --no-cache \
        curl \
        gcc \
        libressl-dev \
        musl-dev \
        libffi-dev && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal && \
    source $HOME/.cargo/env && \
    pip install --no-cache-dir poetry==${POETRY_VERSION} && \
    apk del \
        curl \
        gcc \
        libressl-dev \
        musl-dev \
        libffi-dev

COPY ./pyproject.toml .
COPY ./poetry.lock .

RUN poetry install --no-root

COPY ./src /app/src

EXPOSE 8000

ENV PY_ENV=local
ENV PYTHON_ENV=test
ENV DOMAIN_NAME=localhost
ENV ACTIVE_IP=1.1.1.1
ENV PASSIVE_IP=2.2.2.2
ENV NAMESPACE=e4ca1d-dev

ENTRYPOINT ["poetry", "run"]
CMD ["python", "src/main.py"]
