replicaCount: 3

additionalServerOptions: >-
  -Djgroups.dns.query=sso-keycloak-ping.eb75ad-dev.svc.cluster.local

extraEnvs:
  - name: KC_HOSTNAME
    value: https://dev.loginproxy.gov.bc.ca/auth/
  - name: KC_HOSTNAME_ADMIN
    value: https://dev.loginproxy.gov.bc.ca/auth/
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_BACKUP_INDEX
    value: "21"
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_FILE_SIZE
    value: 300M
  - name: QUARKUS_LOG_FILE_ROTATION_FILE_SUFFIX
    value: .zip
  ## If debugging needs to be done without the use of the vanity urls, use the following KC_HOSTNAMES
  # - name: KC_HOSTNAME
  #   value: https://sso-keycloak-eb75ad-dev.apps.gold.devops.gov.bc.ca/auth/
  # - name: KC_HOSTNAME_ADMIN
  #   value: https://sso-keycloak-eb75ad-dev.apps.gold.devops.gov.bc.ca/auth/

resources:
  limits:
    cpu: 4

persistentLog:
  size: 15Gi

podDisruptionBudget:
  enabled: true
  minAvailable: 2
  maxUnavailable:

patroni:
  replicaCount: 3

  persistentVolume:
    size: 10Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: true

rollingUpdate:
  maxSurge: 1
