replicaCount: 3

additionalServerOptions: >-
  -Djgroups.dns.query=sso-keycloak-ping.eb75ad-prod.svc.cluster.local

extraEnvs:
  - name: KC_HOSTNAME
    value: https://loginproxy.gov.bc.ca/auth/
  - name: KC_HOSTNAME_ADMIN
    value: https://loginproxy.gov.bc.ca/auth/
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_BACKUP_INDEX
    value: "14"
  - name: QUARKUS_LOG_FILE_ROTATION_MAX_FILE_SIZE
    value: 300M
  - name: QUARKUS_LOG_FILE_ROTATION_FILE_SUFFIX
    value: .zip
  ## If debugging needs to be done without the use of the vanity urls, use the following KC_HOSTNAMES
  # - name: KC_HOSTNAME
  #   value: https://sso-keycloak-eb75ad-prod.apps.gold.devops.gov.bc.ca/auth/
  # - name: KC_HOSTNAME_ADMIN
  #   value: https://sso-keycloak-eb75ad-prod.apps.gold.devops.gov.bc.ca/auth/

resources:
  limits:
    cpu: 4
  requests:
    cpu: 150m

persistentLog:
  size: 20Gi

podDisruptionBudget:
  enabled: true
  minAvailable: 2
  maxUnavailable:

patroni:
  replicaCount: 3

  persistentVolume:
    size: 30Gi

  podDisruptionBudget:
    enabled: true

  transportServerClaim:
    enabled: true

  resources:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 50m
      memory: 1.5Gi
