name: Login Openshift Gold & Golddr

inputs:
  namespace:
    description: "The namespace to run the scripts"
    required: true

runs:
  using: composite
  steps:
    - name: Login Gold
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
        namespace: ${{ inputs.namespace }}
        insecure_skip_tls_verify: true
      continue-on-error: true

    - name: Login Golddr
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}
        namespace: ${{ inputs.namespace }}
        insecure_skip_tls_verify: true
      continue-on-error: true
