name: Set the DR deployment to standby

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev","c6af30-test","c6af30-prod", "eb75ad-dev", "eb75ad-test", "eb75ad-prod"]
      deleteDRpvc:
        description: "If the xlogs won't synch between patroni-dr and patroni-gold, delete the dr pvcs and config"
        type: boolean
        required: false
        default: false

jobs:
  transition-scripts:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Login Openshift Gold & Golddr
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ github.event.inputs.namespace }}
          oc-server-gold: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
          oc-token-gold: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
          oc-server-golddr: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          oc-token-golddr: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}

      - name: Run transition script
        run: |
          chmod +x ./set-dr-to-standby.sh
          ./set-dr-to-standby.sh ${{ github.event.inputs.namespace }} ${{ github.event.inputs.deleteDRpvc }}
        working-directory: transition-scripts
