name: Set the DR deployment to standby

on:
  workflow_dispatch:
    inputs:
      project:
        description: "The target project"
        type: choice
        required: true
        options: ["SANDBOX", "PRODUCTION", "OLD-SANDBOX"]
        default: "SANDBOX"
      environment:
        description: "env to deploy"
        type: choice
        options: ["dev","test","prod"]
        default: "dev"
      deleteDRpvc:
        description: "If the xlogs won't synch between patroni-dr and patroni-gold, delete the dr pvcs and config"
        type: boolean
        required: false
        default: false

jobs:
  transition-scripts:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set the deployment namespace
        run: |
          chmod +x ./namespace-setter.sh
          ./namespace-setter.sh ${{ github.event.inputs.project }} ${{ github.event.inputs.environment }}
        working-directory: .github/helpers
      - name: Login Openshift Gold & Golddr
        uses: ./.github/actions/oc-login
        with:
          namespace: $NAMESPACE
          oc-server-gold: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
          oc-token-gold: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
          oc-server-golddr: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          oc-token-golddr: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}

      - name: Run transition script
        run: |
          echo "Running on the $NAMESPACE namespace"
          chmod +x ./set-dr-to-standby.sh
          ./set-dr-to-standby.sh $NAMESPACE ${{ github.event.inputs.deleteDRpvc }}
        working-directory: transition-scripts
