name: Set the Gold deployment to active

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev", "eb75ad-dev", "eb75ad-test", "eb75ad-prod"]

jobs:
  transition-scripts:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Login Openshift Gold & Golddr
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ github.event.inputs.namespace }}
          oc-server-gold: https://api.fakegold.devops.gov.bc.ca:6666
          oc-token-gold: ${{ secrets.OPENSHIFT_TOKEN_GOLD }}
          oc-server-golddr: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          oc-token-golddr: ${{ secrets.OPENSHIFT_TOKEN_GOLDDR }}

      - name: Run transition script
        run: |
          chmod +x ./switch-to-gold.sh
          ./switch-to-gold.sh ${{ github.event.inputs.namespace }}
        working-directory: transition-scripts
