name: Run test workflows

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "The target namespace"
        required: true
        options: ["c6af30-dev"]

jobs:
  transition-scripts:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Login Openshift Gold & Golddr
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ github.event.inputs.namespace }}
          oc-server-gold: ${{ secrets.OPENSHIFT_SERVER_GOLD }}
          oc-token-gold: ${{ secrets[format('OPENSHIFT_TOKEN_GOLD_{0}', github.event.inputs.project)] }}
          oc-server-golddr: ${{ secrets.OPENSHIFT_SERVER_GOLDDR }}
          oc-token-golddr: ${{ secrets[format('OPENSHIFT_TOKEN_GOLDDR_{0}', github.event.inputs.project)] }}

      - name: Run transition script
        run: |
          chmod +x ./test-workflows.sh
          ./test-workflows.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.namespace }}
        working-directory: transition-scripts
